export const LOGOUT = 'LOGOUT'
export const SAVE_USER = 'SAVE_USER'
export const SAVE_MENU_CARDS = 'SAVE_MENU_CARDS'
export const SAVE_MENU_LIST = 'SAVE_MENU_LIST'
export const SAVE_MENU_LIST_CHILDREN_FOR_TREE_SELECT =
  'SAVE_MENU_LIST_CHILDREN_FOR_TREE_SELECT'

export const SAVE_MENU_LIST_CHILDREN_FOR_ALL_INFO =
  'SAVE_MENU_LIST_CHILDREN_FOR_ALL_INFO'
export const CLEAR_REDUX_STATE = 'CLEAR_REDUX_STATE'
